### ISSUE TITLE
[Off] Autologin ?

### ISSUE THREAD

**Issue by guimafx** [salaros/vtwsclib-php#14]
Hello guys, is that possible to make some AUTOLOGIN with vtiger webservices auth, and then, redirect the user to the vtiger instance ?

[vtigerUrl:protected] => http://www.urlvtigercrm.com.br/vtigercrm/
  | [wsBaseURL:protected] => webservice.php
  | [vtigerApiVersion:Salaros\Vtiger\VTWSCLib\Session:private] => 0.22
  | [vtigerVersion:Salaros\Vtiger\VTWSCLib\Session:private] => 7.1.0
  | [serviceExpireTime:Salaros\Vtiger\VTWSCLib\Session:private] => 1519933899
  | [serviceToken:Salaros\Vtiger\VTWSCLib\Session:private] => 5a98589f9eb44
  | [userName:Salaros\Vtiger\VTWSCLib\Session:private] => admin
  | [accessKey:Salaros\Vtiger\VTWSCLib\Session:private] => 92sj22h2hh2syy2
  | [userID:Salaros\Vtiger\VTWSCLib\Session:private] => 19x1
  | [sessionName:Salaros\Vtiger\VTWSCLib\Session:private] => 530bbbf55a98589fc92af

**Comment by salaros** [comment]
vtwsclib is just a vTiger API client, it doesn't affect vTiger web session at all.
Web interface and API are like a PC and a Mac reading the information from the same network attached hard drive, you cannot use the PC to write some information to the hard drive in order to auto-login the Mac user
