### ISSUE TITLE
Update Sales Order, removes Items 

### ISSUE THREAD

**Issue by amahdavy** [salaros/vtwsclib-php#15]
When I update an existing Sales order it remove all items from sales order.
Below you can find my code. Please help me to find issue.
I developed my code in 2 styles and every 2 styles has this issue :
1-
function update_sales_order($id)
{
$client = new WSClient(VTIGER_URL, VTIGER_API_USER, VTIGER_API_KEY);
$UpdSOrder = $client->entities->findOneByID('SalesOrder', $id,[] );
$UpdSOrder['invoicestatus'] = 'Cancel';
$UpdSOrder['subject'] = 'TEST2-FOR-IT- ';
$entities = $client->entities->updateOne('SalesOrder', $id, $UpdSOrder);
return $entities;
}
2-
function update_sales_order($id)
{
$client = new WSClient(VTIGER_URL, VTIGER_API_USER, VTIGER_API_KEY);
$UpdSOrder = array(
'invoicestatus' => 'Cancel',
'subject' => 'TEST2-FOR-IT- '
);
$entities = $client->entities->updateOne('SalesOrder', $id, $UpdSOrder);
return $entities;
}

**Comment by salaros** [comment]
Hi there, that's a pretty strange bug. Please give me more information about your vTiger/PHP version

**Comment by amahdavy** [comment]
Hi,

VTiger version is 7.0 and my php version is 5.6.30.

**Comment by salaros** [comment]
OK, I will try to reproduce it. Sorry if it takes so long, but sometimes it's pretty hard for me to find time for my open-source projects on workdays

**Comment by salaros** [comment]
So I discovered what's the reason for such malfunctioning: vTiger has two ways to retrieve records (entities) using web services. For instance I was using 'query' WS operation which is more flexible, while only 'retrieve' seems to work correctly with entities with so-called LineItems aka Products / Services etc

@amahdavy thanks for your help and sorry if it took so long to get it fixed

**Comment by salaros** [comment]
```php
<?php

require_once 'vendor/autoload.php';

use Salaros\Vtiger\VTWSCLib\WSClient;

define('VTIGER_URL', 'http://yourcrm.com');
define('VTIGER_API_USER', 'user');
define('VTIGER_API_KEY', 'aPiK3y');

function update_sales_order($id)
{
        $client = new WSClient(VTIGER_URL, VTIGER_API_USER, VTIGER_API_KEY);
        $UpdSOrder = $client->entities->findOneByID('SalesOrder', $id);
        $UpdSOrder['enable_recurring'] = 1;
        $UpdSOrder['invoicestatus'] = 'Cancel';
        $UpdSOrder['subject'] = 'TEST2-FOR-IT-';
        $entities = $client->entities->updateOne('SalesOrder', $id, $UpdSOrder);
        return $entities;
}

$client = new WSClient(VTIGER_URL, VTIGER_API_USER, VTIGER_API_KEY);
$result = update_sales_order(4);
```
